"""Agregar columna tipo a rutas_fijas

Revision ID: 2a7fd9df08f0
Revises: 8826cb81cf6d
Create Date: 2025-08-14 23:31:18.150143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a7fd9df08f0'
down_revision: Union[str, Sequence[str], None] = '8826cb81cf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vinculos_apoderado_conductor')
    op.add_column('rutas_fijas', sa.Column('tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas_fijas', 'tipo')
    op.create_table('vinculos_apoderado_conductor',
    sa.Column('id_vinculo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_apoderado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_conductor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_vinculacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_apoderado'], ['apoderados.id_apoderado'], name=op.f('vinculos_apoderado_conductor_id_apoderado_fkey')),
    sa.ForeignKeyConstraint(['id_conductor'], ['conductores.id_conductor'], name=op.f('vinculos_apoderado_conductor_id_conductor_fkey')),
    sa.PrimaryKeyConstraint('id_vinculo', name=op.f('vinculos_apoderado_conductor_pkey'))
    )
    # ### end Alembic commands ###
