"""Base limpia sin direcciones

Revision ID: 5a814a4bd872
Revises: 
Create Date: 2025-07-05 16:22:57.336760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a814a4bd872'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asistencias', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('rutas_fijas', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rutas_fijas', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('asistencias', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
