"""Agrega cascada en relaciones estudiante y apoderado

Revision ID: 64cffcd54cc8
Revises: 2a7fd9df08f0
Create Date: 2025-08-18 22:25:42.730595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cffcd54cc8'
down_revision: Union[str, Sequence[str], None] = '2a7fd9df08f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('asistencias_id_estudiante_fkey'), 'asistencias', type_='foreignkey')
    op.create_foreign_key(None, 'asistencias', 'estudiantes', ['id_estudiante'], ['id_estudiante'], ondelete='CASCADE')
    op.drop_constraint(op.f('paradas_id_estudiante_fkey'), 'paradas', type_='foreignkey')
    op.create_foreign_key(None, 'paradas', 'estudiantes', ['id_estudiante'], ['id_estudiante'], ondelete='CASCADE')
    op.drop_constraint(op.f('paradas_ruta_fija_id_ruta_fija_fkey'), 'paradas_ruta_fija', type_='foreignkey')
    op.create_foreign_key(None, 'paradas_ruta_fija', 'rutas_fijas', ['id_ruta_fija'], ['id_ruta_fija'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paradas_ruta_fija', type_='foreignkey')
    op.create_foreign_key(op.f('paradas_ruta_fija_id_ruta_fija_fkey'), 'paradas_ruta_fija', 'rutas_fijas', ['id_ruta_fija'], ['id_ruta_fija'])
    op.drop_constraint(None, 'paradas', type_='foreignkey')
    op.create_foreign_key(op.f('paradas_id_estudiante_fkey'), 'paradas', 'estudiantes', ['id_estudiante'], ['id_estudiante'])
    op.drop_constraint(None, 'asistencias', type_='foreignkey')
    op.create_foreign_key(op.f('asistencias_id_estudiante_fkey'), 'asistencias', 'estudiantes', ['id_estudiante'], ['id_estudiante'])
    # ### end Alembic commands ###
