"""Agrega cascada en relaciones estudiante y apoderado

Revision ID: 76944a14143a
Revises: daf57d4222b2
Create Date: 2025-08-18 22:36:41.672912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76944a14143a'
down_revision: Union[str, Sequence[str], None] = 'daf57d4222b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('paradas_ruta_fija_id_estudiante_fkey'), 'paradas_ruta_fija', type_='foreignkey')
    op.create_foreign_key(None, 'paradas_ruta_fija', 'estudiantes', ['id_estudiante'], ['id_estudiante'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paradas_ruta_fija', type_='foreignkey')
    op.create_foreign_key(op.f('paradas_ruta_fija_id_estudiante_fkey'), 'paradas_ruta_fija', 'estudiantes', ['id_estudiante'], ['id_estudiante'])
    # ### end Alembic commands ###
