"""Agrega cascada en relaciones estudiante y apoderado

Revision ID: daf57d4222b2
Revises: 64cffcd54cc8
Create Date: 2025-08-18 22:29:13.386183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf57d4222b2'
down_revision: Union[str, Sequence[str], None] = '64cffcd54cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('estudiantes_id_apoderado_fkey'), 'estudiantes', type_='foreignkey')
    op.create_foreign_key(None, 'estudiantes', 'apoderados', ['id_apoderado'], ['id_apoderado'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estudiantes', type_='foreignkey')
    op.create_foreign_key(op.f('estudiantes_id_apoderado_fkey'), 'estudiantes', 'apoderados', ['id_apoderado'], ['id_apoderado'])
    # ### end Alembic commands ###
