"""Agregar campo tipo a rutas

Revision ID: dfa0f5a675c9
Revises: 76944a14143a
Create Date: 2025-08-22 13:13:00.702246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa0f5a675c9'
down_revision: Union[str, Sequence[str], None] = '76944a14143a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutas', sa.Column('tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'tipo')
    # ### end Alembic commands ###
